-- Oilplot oil-only schema (src_/dim_/fact_ tables).
-- This migration is additive; it creates the oil repository tables without removing construction/project tables.

CREATE TABLE IF NOT EXISTS "dim_countries" (
	"iso_code" varchar(3) PRIMARY KEY,
	"country_name" text NOT NULL,
	"region" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dim_oil_types" (
	"id" serial PRIMARY KEY,
	"code" text NOT NULL UNIQUE,
	"name" text NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dim_oil_types_app" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"code" text NOT NULL UNIQUE,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dim_refineries" (
	"ref_id" serial PRIMARY KEY,
	"name" text NOT NULL,
	"country_code" varchar(3),
	"capacity_kbd" integer,
	"operator" text,
	"type" text DEFAULT 'Refinery',
	"gps_lat" numeric(9, 6),
	"gps_long" numeric(9, 6)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dim_wells" (
	"well_id" serial PRIMARY KEY,
	"well_name" text NOT NULL,
	"field_name" text,
	"country_code" varchar(3),
	"well_size_category" text,
	"discovery_date" date,
	"gps_lat" numeric(9, 6),
	"gps_long" numeric(9, 6)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fact_prices" (
	"price_id" serial PRIMARY KEY,
	"oil_type_id" integer UNIQUE,
	"price_usd_per_bbl" numeric(10, 2),
	"market_location" text UNIQUE,
	"price_date" date NOT NULL UNIQUE
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fact_prices_app" (
	"id" serial PRIMARY KEY,
	"oil_type_id" integer NOT NULL UNIQUE,
	"price_date" date NOT NULL UNIQUE,
	"close_price" numeric(18, 6) NOT NULL,
	"change_percent" numeric(10, 4),
	"src" text NOT NULL UNIQUE,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fact_production" (
	"prod_id" serial PRIMARY KEY,
	"country_code" varchar(3),
	"ref_id" integer,
	"oil_type_id" integer,
	"volume_barrels" integer,
	"report_date" date NOT NULL,
	"is_forecast" boolean DEFAULT false,
	"src_id" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fact_shipments" (
	"shipment_id" serial PRIMARY KEY,
	"origin_country" varchar(3),
	"dest_refinery_id" integer,
	"oil_type_id" integer,
	"volume_barrels" integer,
	"arrival_date" date,
	"route_name" text,
	"status" text DEFAULT 'Completed'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fact_well_output" (
	"output_id" serial PRIMARY KEY,
	"well_id" integer,
	"daily_barrels" integer,
	"water_cut_pct" numeric(5, 2),
	"report_date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "src_scraper_logs" (
	"log_id" serial PRIMARY KEY,
	"scraper_name" text NOT NULL,
	"run_time" timestamp DEFAULT CURRENT_TIMESTAMP,
	"rows_inserted" integer,
	"status" text,
	"error_message" text,
	"raw_response_json" jsonb
);
--> statement-breakpoint

-- Foreign keys
ALTER TABLE "dim_refineries" ADD CONSTRAINT "dim_refineries_country_code_fkey"
	FOREIGN KEY ("country_code") REFERENCES "dim_countries"("iso_code");
--> statement-breakpoint
ALTER TABLE "dim_wells" ADD CONSTRAINT "dim_wells_country_code_fkey"
	FOREIGN KEY ("country_code") REFERENCES "dim_countries"("iso_code");
--> statement-breakpoint
ALTER TABLE "fact_prices" ADD CONSTRAINT "fact_prices_oil_type_id_fkey"
	FOREIGN KEY ("oil_type_id") REFERENCES "dim_oil_types"("id");
--> statement-breakpoint
ALTER TABLE "fact_prices_app" ADD CONSTRAINT "fact_prices_app_oil_type_id_fkey"
	FOREIGN KEY ("oil_type_id") REFERENCES "dim_oil_types_app"("id");
--> statement-breakpoint
ALTER TABLE "fact_production" ADD CONSTRAINT "fact_production_country_code_fkey"
	FOREIGN KEY ("country_code") REFERENCES "dim_countries"("iso_code");
--> statement-breakpoint
ALTER TABLE "fact_production" ADD CONSTRAINT "fact_production_oil_type_id_fkey"
	FOREIGN KEY ("oil_type_id") REFERENCES "dim_oil_types"("id");
--> statement-breakpoint
ALTER TABLE "fact_production" ADD CONSTRAINT "fact_production_ref_id_fkey"
	FOREIGN KEY ("ref_id") REFERENCES "dim_refineries"("ref_id");
--> statement-breakpoint
ALTER TABLE "fact_shipments" ADD CONSTRAINT "fact_shipments_dest_refinery_id_fkey"
	FOREIGN KEY ("dest_refinery_id") REFERENCES "dim_refineries"("ref_id");
--> statement-breakpoint
ALTER TABLE "fact_shipments" ADD CONSTRAINT "fact_shipments_oil_type_id_fkey"
	FOREIGN KEY ("oil_type_id") REFERENCES "dim_oil_types"("id");
--> statement-breakpoint
ALTER TABLE "fact_shipments" ADD CONSTRAINT "fact_shipments_origin_country_fkey"
	FOREIGN KEY ("origin_country") REFERENCES "dim_countries"("iso_code");
--> statement-breakpoint
ALTER TABLE "fact_well_output" ADD CONSTRAINT "fact_well_output_well_id_fkey"
	FOREIGN KEY ("well_id") REFERENCES "dim_wells"("well_id");

